apiVersion: v1
kind: Secret
metadata:
  name: telemetry-api-secrets
  namespace: default
type: Opaque
stringData:
  DATABASE_URL: "postgresql+asyncpg://pgadmin:SC-t3l3m3try-2026!@postgres/telemetry"
  API_KEY: "17a6694ceafa61311f140711840fb635e7350296917c9f1f5d1513384d6f538d"
  POSTGRES_USER: "pgadmin"
  POSTGRES_PASSWORD: "SC-t3l3m3try-2026!"
